### ISSUE TITLE
CocoaPods seems incorrect

### ISSUE THREAD

**Issue by btrzupek** [kysomers/CheckboxList#1]
When CocoaPods imports your library into my project, the ChecklistView.swift has a public class, but the functions are NOT public so I cannot call:

https://github.com/kysomers/CheckboxList/blob/master/CheckboxListSwift/ChecklistView.swift
- setColor
- setShape
- checkboxSetup

The file is here and the functions ARE correctly listed as public, but again - when pulled with Cocoapods they are not and thus you cannot use the library straight out of Cocopods.

**Comment by kysomers** [comment]
You're absolutely right. I remember fixing it a few months ago then getting distracted before updating Cocopods with the fix. I'll resolve it soon. Thanks for reminding me.

**Comment by kysomers** [comment]
Pushed an update to Cocoapods with the issue fixed
